spring.datasource.url=jdbc:postgresql://localhost:5432/HAHA
spring.datasource.username=postgres
spring.datasource.password=Clemencea
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=dGhpcyBpcyBhIHNhZmUgdGVzdCBzZWNyZXQga2V5IGZvciBkZXZlbG9wbWVudA==
app.jwt.expiration-ms=86400000
app.stock.low-threshold=10